version: "3.9"
services:
  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: "2gb"
    ports:
      - "4444:4444"

  wdio:
    build: .
    depends_on:
      - chrome
    environment:
      - WDIO_BASE_URL=http://selenium:4444
